// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHs6BIQQ94XJnaSibvL5f-D6Nx-MoT_o',
    appId: '1:982006532490:web:5a9690aa26b6b70904e073',
    messagingSenderId: '982006532490',
    projectId: 'firstapp2026-7bb37',
    authDomain: 'firstapp2026-7bb37.firebaseapp.com',
    storageBucket: 'firstapp2026-7bb37.firebasestorage.app',
    measurementId: 'G-KZ9ZHMJX0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoVdgNFNq_mNd6yFWqLoA0xJ9As2-aSNE',
    appId: '1:982006532490:android:80a8ed35d30596e504e073',
    messagingSenderId: '982006532490',
    projectId: 'firstapp2026-7bb37',
    storageBucket: 'firstapp2026-7bb37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh99TgiUybod4jgWgDam_AdCELFAKX6pw',
    appId: '1:982006532490:ios:a0f66b605fc37cd904e073',
    messagingSenderId: '982006532490',
    projectId: 'firstapp2026-7bb37',
    storageBucket: 'firstapp2026-7bb37.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh99TgiUybod4jgWgDam_AdCELFAKX6pw',
    appId: '1:982006532490:ios:a0f66b605fc37cd904e073',
    messagingSenderId: '982006532490',
    projectId: 'firstapp2026-7bb37',
    storageBucket: 'firstapp2026-7bb37.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzHs6BIQQ94XJnaSibvL5f-D6Nx-MoT_o',
    appId: '1:982006532490:web:02807d4ebcebab5004e073',
    messagingSenderId: '982006532490',
    projectId: 'firstapp2026-7bb37',
    authDomain: 'firstapp2026-7bb37.firebaseapp.com',
    storageBucket: 'firstapp2026-7bb37.firebasestorage.app',
    measurementId: 'G-ZWQ8PMCE78',
  );
}
